---
title: "Untitled"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tigris); options(tigris_use_cache = TRUE, tigris_class = "sf")
library(sf)
library(tidyverse)
```



Shapes.

```{r message=FALSE, warning=FALSE}
nm_house_districts <- tigris::state_legislative_districts('New Mexico', 
                                                  house = "lower", 
                                                  cb = TRUE)  %>%
  select(GEOID, NAME)

nm_senate_districts <- tigris::state_legislative_districts('New Mexico', 
                                                  house = "upper", 
                                                  cb = TRUE) %>%
  select(GEOID, NAME)

us_house_districts <- tigris::congressional_districts(cb = TRUE) %>%
  filter(STATEFP == '35') %>%
  select(GEOID, CD115FP) %>% 
  rename(NAME=CD115FP)
  
nm_counties <- tigris::counties(state='New Mexico', cb = TRUE) %>%
  select(GEOID, NAME) %>%
  sf::st_set_crs(sf::st_crs(nmelectiondatr::nmel_pol_geos$nm_house_districts))

nm_places <- tigris::places(state='New Mexico', cb = TRUE) %>%
  select(GEOID, NAME, LSAD)


nm_counties$NAME[grep('a Ana', nm_counties$NAME)] <- 'Dona Ana'
#st_crs(us_house_districts)
#st_transform(26913)  
#For leaflet --- #sf::st_set_crs('+proj=longlat +datum=WGS84')
```



Available [here](https://github.com/nvkelso/election-geodata).  NOTE (& keep a record of.):  Precinct shapefile from `tigris` has n = 1448 unique county/precints.  Precinct shapefile from Git: 1483.  Election results from NM_SOS 2016 & 2018: 1492.  11 precincts exist in NM_SOS election data that do not exist in shapefile via Git.  (in fed HDs 2 & 3).

```{r message=TRUE, warning=TRUE}
#nm_prec_tigris <- tigris::voting_districts('New Mexico') 

nm_precincts <- sf::st_read ("C:\\Users\\jason\\Google Drive\\GitHub\\packages\\nmelectiondatr\\data-raw\\nm-2012-precincts","precincts_2012")%>%
  mutate(County_Name = gsub(' County.*$', '', NAME10),
         NAME10 = paste0(County_Name, gsub('(^.*)( County.*$)', '\\2', NAME10))) %>%
  rename(Precinct_Num = prec_num) %>%
  select(NAME10, County_Name, Precinct_Num)

nm_precincts$County_Name[grep('a Ana', nm_precincts$County_Name)] <- 'Dona Ana'

#US House district, NM House districts, NM Senate Districts, 
geos <- nmel_results_precinct %>%
  filter(Type %in% c('State Senator', 'State Representative', 'United States Representative')&
           Year == 2016) %>%
  select(Type, Type_Sub, Precinct_Num, County_Name) %>%
  group_by(Type, Type_Sub, County_Name, Precinct_Num) %>%
  distinct() %>%
  ungroup() 
  
geos <- geos[-4163,]
geos <- geos %>%
  spread(Type, Type_Sub)%>%
  rename(State_Senate = `State Senator`,
         State_Rep = `State Representative`,
         CD = `United States Representative`)

nm_precincts <- nm_precincts %>% left_join(geos)

crs <- sf::st_crs("+proj=longlat +datum=NAD83 +no_defs") # Lambert equal area
nm_precincts <- sf::st_transform(nm_precincts, crs = crs)
st_crs(nm_precincts)$proj4string <- "+proj=longlat +datum=NAD83 +no_defs"
```



Simple list object:

```{r}
nmel_pol_geos <- list('nm_counties' = nm_counties, 
                      'nm_places' = nm_places,
                      'nm_precincts' = nm_precincts,
                      'nm_senate_districts' = nm_senate_districts, 
                      'nm_house_districts' = nm_house_districts, 
                      'us_congress_districts'= us_house_districts)
```




###6. Output, etc. 

```{r eval=FALSE, include=FALSE}
setwd("C:\\Users\\jason\\Google Drive\\GitHub\\packages\\nmelectiondatr")
devtools::use_data(nmel_pol_geos, overwrite=TRUE)
```

